# Generated by Django 4.1.7 on 2023-02-18 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="descriptiom",
            new_name="description",
        ),
    ]
