# Generated by Django 4.1.7 on 2023-02-18 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_rename_descriptiom_products_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="catrgory",
            new_name="category",
        ),
    ]
